#*********************************************************************************
#                                                                                *
# This file is part of the "KMIP Asymmetric key demo" project.                   *
# Use it at your own risk                                                        *
# Distributed under Apache 2.0 license                                           *
#                                                                                *
# Written by Erik LOUISE                                                         *
# Copyright © 2025 Thales Group                                                  *
#                                                                                *
#*********************************************************************************

# OBJECTIVE :
# - Store common configuration for create_keypair.py, decrypt_in_ctm_with_private_key.py & encrypt_locally_with_public_key_from_ctm.py files

CTM_HOST = "kmip.ciphertrustmanager.local"                                           # Hostname or IP address of your CipherTrust Manager appliance                                                                      # Port of the KMIP server of the Ciphertrust Manager instance       
CTM_USER = "REST_USER"                                          # Username to connect to the CipherTrust Manager instance
CTM_PASSWORD = "RestPassword123*"                               # Password to connect to the CipherTrust Manager instance
ASYM_ALGO = "RSA"                                               # Asymmetric key algorithm
ASYM_KEY_LENGTH = 4096                                          # 512, 1024, 2048, 3072 or 4096
ASYM_KEY_NAME = "DemoREST"                                      # Set what you want but different from the Private Key name
ASYM_KEY_USAGE_MASK = 124                                          # 4 (Encrypt) + 8 (Decrypt) + 16 (Wrap Key) + 32 (Unwrap Key) + 64 (Export) = 124
PUBLIC_KEYID_FILE = f'./secrets/{ASYM_KEY_NAME}_ID.txt'         # You'd rather not touch that
PRIVATE_KEYID_FILE = f'../secrets/{ASYM_KEY_NAME}_ID.txt'       # You'd also rather not touch that
AES_KEY_FILE="../secrets/aes_gcm_key.bin"                       # AES Key file, generated by generate_aes_key.sh
AES_IV_FILE="../secrets/aes_gcm_iv.bin"                         # AES IV file, generated by generate_aes_key.sh
AES_WRAPPED_KEY_FILE="../secrets/aes_gcm_key.wrapped"           # RSA wrapped AES key file, generated by encrypt_locally_with_public_key_from_ctm.sh