#*********************************************************************************
#                                                                                *
# This file is part of the "KMIP Asymmetric key demo" project.                   *
# Use it at your own risk                                                        *
# Distributed under Apache 2.0 license                                           *
#                                                                                *
# Written by Erik LOUISE                                                         *
# Copyright © 2025 Thales Group                                                  *
#                                                                                *
#*********************************************************************************

# OBJECTIVE :
# - Store common configuration for create_keypair.py, decrypt_in_ctm_with_private_key.py & encrypt_locally_with_public_key_from_ctm.py files

KMIP_HOST = "kmip.ciphertrustmanager.local"                     # IP or hostname of the Ciphertrust Manager instance
KMIP_PORT = 5696                                                # Port of the KMIP server of the Ciphertrust Manager instance
CLIENT_CERT = "../secrets/DemoOrg_KMIPClient_client_cert.pem"    # Generated by generate_ctm_kmip_certs.sh, change it accordingly if you changed the kmip-profile.yaml file
CLIENT_KEY = "../secrets/DemoOrg_KMIPClient_client_key.pem"      # Generated by generate_ctm_kmip_certs.sh, change it accordingly if you changed the kmip-profile.yaml file
CA_CERT = "../secrets/Certificate.pem"                           # Downloaded from Ciphertrust Manager (on the default CA, click the 3 dots then 'Download')
KEY_LENGTH = 4096                                               # 512, 1024, 2048, 3072 or 4096
PUBLIC_KEY_NAME = "DemoKMIP_PublicKey"                          # Set what you want but different from the Private Key name
PRIVATE_KEY_NAME = "DemoKMIP_PrivateKey"                        # Set what you want but different from the Public Key name
PUBLIC_KEYID_FILE = f'./secrets/{PUBLIC_KEY_NAME}_ID.txt'       # You'd rather not touch that
PRIVATE_KEYID_FILE = f'../secrets/{PRIVATE_KEY_NAME}_ID.txt'     # You'd also rather not touch that
AES_KEY_FILE="../secrets/aes_gcm_key.bin"                        # AES Key file, generated by generate_aes_key.sh
AES_IV_FILE="../secrets/aes_gcm_iv.bin"                          # AES IV file, generated by generate_aes_key.sh
AES_WRAPPED_KEY_FILE="../secrets/aes_gcm_key.wrapped"            # RSA wrapped AES key file, generated by encrypt_locally_with_public_key_from_ctm.sh